/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_barang;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLSyntaxErrorException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOKOWAWW
 */
public class Iventory_Barang extends javax.swing.JFrame {

    private Connection conn;
    private Statement stat;
    private ResultSet res;
    /**
     * Creates new form Iventory_Barang
     */
    public Iventory_Barang() {
   
        
        initComponents();
        setTitle("Inventory Barang");
        koneksi();
        tabel1();
        tabel2();  
       // membuat layout tampil di tengah pada saat di tampilkan
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       Dimension frameSize = getSize();
       setLocation(
        (screenSize.width - frameSize.width)/2,
        (screenSize.height - frameSize.height)/2);
    }
    
       
   private void koneksi(){
       try{
       
           Class.forName("com.mysql.cj.jdbc.Driver"); 
           conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_barang?user=root&pass=");
           
            stat=conn.createStatement();
           } catch (ClassNotFoundException |SQLException e) {
               JOptionPane.showMessageDialog(null,"tidak ada koneksi yang terbuka");
           }
           
           }       
    private void kosongkan(){
        kode.setText("");
        nama.setText("");
        tglm.setText("");
        tglk.setText("");
        jumlah.setText("");
        kategori.setSelectedIndex(-1);
        kode.requestFocus();
    }
    private void tabel1(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Kode_barang");
        t.addColumn("Nama_Barang");
        t.addColumn("Tanggal_Masuk");
        t.addColumn("Jumlah");
        t.addColumn("Kategori");
        String cari = txtcari.getText(); 
        tbl1.setModel(t);try {
            res=stat.executeQuery("select * from inventory_barang_masuk WHERE Nama_barang LIKE'%"+cari+"%'");
                    while (res.next()) {
                        t.addRow(new Object[]{res.getString("Kd_Barang"),
                            res.getString("Nama_Barang"),
                            res.getString("Tanggal_Masuk"),
                            res.getString("Jumlah"),
                            res.getString("Kategori"),   
                        });
        }
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    private void tabel2(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Kode_barang");
        t.addColumn("Nama_Barang");
        t.addColumn("Tanggal_Masuk");
        t.addColumn("Tanggal_keluar");
        t.addColumn("Jumlah");
        t.addColumn("Kategori");
         String cari1 = txtcari2.getText(); 
        tbl2.setModel(t);try {
            res=stat.executeQuery("select * from inventory_barang_keluar WHERE Nama_barang LIKE'%"+cari1+"%'");
                    while (res.next()) {
                        t.addRow(new Object[]{res.getString("Kd_Barang"),
                            res.getString("Nama_Barang"),
                            res.getString("Tanggal_Masuk"),
                            res.getString("Tanggal_keluar"),
                            res.getString("Jumlah"),
                            res.getString("Kategori"),   
                        });
        }
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }
private void kategori(){
    kategori.addItem("laptop");
        kategori.addItem("PC / Komputer");
        kategori.addItem("Monitor");
        kategori.addItem("Aksesoris komputer");
        kategori.addItem("hardware");
        kategori.setSelectedIndex(-1);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kategorilbl = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tglm = new javax.swing.JTextField();
        tglk = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        masuk = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        Cari = new javax.swing.JButton();
        hapus2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcari2 = new javax.swing.JTextField();
        hapus3 = new javax.swing.JButton();
        Cari1 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(133, 0, 226));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROGRAM INVENTORY BARANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 20, 290, 36);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE BARANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 110, 110, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA BARANG");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 150, 104, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TANGGAL MASUK");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 121, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TANGGAL KELUAR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 140, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JUMLAH");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 270, 60, 30);

        kategorilbl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        kategorilbl.setForeground(new java.awt.Color(255, 255, 255));
        kategorilbl.setText("KATEGORI");
        jPanel1.add(kategorilbl);
        kategorilbl.setBounds(20, 310, 80, 30);

        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        jPanel1.add(kode);
        kode.setBounds(170, 110, 136, 30);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama);
        nama.setBounds(170, 150, 136, 30);
        jPanel1.add(tglm);
        tglm.setBounds(170, 190, 136, 30);
        jPanel1.add(tglk);
        tglk.setBounds(170, 230, 136, 30);
        jPanel1.add(jumlah);
        jumlah.setBounds(170, 270, 136, 30);

        edit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(230, 380, 77, 30);

        refresh.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(230, 430, 77, 30);

        clear.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(230, 480, 77, 30);

        exit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(230, 530, 77, 35);

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl1.setAlignmentX(0.6F);
        tbl1.setAlignmentY(0.6F);
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 150, 640, 180);

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(330, 380, 640, 190);

        masuk.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        masuk.setText("Barang Masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        jPanel1.add(masuk);
        masuk.setBounds(510, 110, 115, 30);

        keluar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        keluar.setText("Barang Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(510, 340, 113, 30);

        Cari.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        jPanel1.add(Cari);
        Cari.setBounds(730, 340, 70, 30);

        hapus2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hapus2.setText("Hapus");
        hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus2ActionPerformed(evt);
            }
        });
        jPanel1.add(hapus2);
        hapus2.setBounds(640, 340, 69, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_barang/imege/ICON IVENTORI INPUT DATA.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 380, 190, 210);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("                                                               INPUT DATA BARANG                                                      ");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 51, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(255, 204, 255)));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 60, 820, 30);

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "PC / Komputer", "Monitor", "Aksesoris komputer", "hardware", " " }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        jPanel1.add(kategori);
        kategori.setBounds(170, 310, 130, 30);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STOCK BARANG MASUK");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 120, 180, 29);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("STOCK BARANG KELUAR");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 350, 180, 29);

        txtcari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari2);
        txtcari2.setBounds(810, 340, 160, 30);

        hapus3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hapus3.setText("Hapus");
        hapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus3ActionPerformed(evt);
            }
        });
        jPanel1.add(hapus3);
        hapus3.setBounds(640, 110, 69, 30);

        Cari1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Cari1.setText("Cari");
        Cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cari1);
        Cari1.setBounds(730, 110, 70, 30);

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari);
        txtcari.setBounds(810, 110, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1012, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
        try{
            stat.executeUpdate("insert into inventory_barang_masuk values ("
            + "'" + kode.getText()+"',"
            + "'" + nama.getText()+"',"
            + "'" + tglm.getText()+"',"
            + "'" + jumlah.getText()+"',"
            + "'" + kategori.getSelectedItem()+ "')");
            //DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
            //model.setRowCount(0);
             DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
            model.setRowCount(0);
            tabel1();
            tabel2();
            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
        }catch (Exception e){
                JOptionPane.showMessageDialog(null, "perintah salah : "+e);
        }
            
    }//GEN-LAST:event_masukActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
    try{
    res=stat.executeQuery("select * from inventory_barang_masuk where  Kd_Barang='" + kode.getText()
    +"'"); while (res.next()){
    nama.setText(res.getString("Nama_Barang"));
    tglm.setText(res.getString("Tanggal_masuk"));
    jumlah.setText(res.getString("Jumlah"));
    kategori.setSelectedItem(res.getString("Kategori"));
}
     }                                     
    catch(Exception e){
                 JOptionPane.showMessageDialog(rootPane, e);
}
    }//GEN-LAST:event_kodeActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentHidden

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed

        


    
        
    }//GEN-LAST:event_kategoriActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       try{
            stat.executeUpdate("insert into inventory_barang_keluar values ("
            + "'" + kode.getText()+"',"
            + "'" + nama.getText()+"',"
            + "'" + tglm.getText()+"',"
            + "'" + tglk.getText()+"',"
            + "'" + jumlah.getText()+"',"
            + "'" + kategori.getSelectedItem()+"')");
            this.tabel1();
            this.tabel2();
            kosongkan();
            JOptionPane.showMessageDialog(null, "data Berhasil di keluarkan ");
        }catch (Exception e){
                JOptionPane.showMessageDialog(null, "perintah salah : "+e);
        }  
    }//GEN-LAST:event_keluarActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
      int i = tbl1.getSelectedRow();
      if(i==-1){
      return;
      }
      String code = (String)tbl1.getValueAt(i,0);
      String code1 = (String)tbl1.getValueAt(i,1);
      String code2 = (String)tbl1.getValueAt(i,2);
      String code3 = (String)tbl1.getValueAt(i,3);
      String code4 = (String)tbl1.getValueAt(i,4);
      kode.setText(code);
      nama.setText(code1);
      tglm.setText(code2);
      jumlah.setText(code3);
      kategori.setSelectedItem(code4);
      
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
       int i = tbl2.getSelectedRow();
       if(i==-1){
           return;
       }
      String code = (String)tbl2.getValueAt(i,0);
      String code1 = (String)tbl2.getValueAt(i,1);
      String code2 = (String)tbl2.getValueAt(i,2);
      String code3 = (String)tbl2.getValueAt(i,3);
      String code4 = (String)tbl2.getValueAt(i,4);
      String code5 = (String)tbl2.getValueAt(i,5);
      kode.setText(code);
      nama.setText(code1);
      tglm.setText(code2);
      tglk.setText(code3);
      tglk.setText(code4);
      kategori.setSelectedItem(code5);
       
    }//GEN-LAST:event_tbl2MouseClicked

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
    tabel2();
    }//GEN-LAST:event_CariActionPerformed

    private void hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus2ActionPerformed
       int ok = JOptionPane.showConfirmDialog(null,"apakah anda yakin untuk menghapus data ini???",
               "confirmation",JOptionPane.YES_NO_OPTION);
        try {
            stat.executeUpdate("DELETE FROM inventory_barang_keluar where Kd_Barang='"+kode.getText()
            +"'");
            
            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah salah"+e);
        }
    }//GEN-LAST:event_hapus2ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
    DefaultTableModel model = (DefaultTableModel)tbl1.getModel();
    model.setRowCount(0);
    tabel1();
    tabel2();
    
    }//GEN-LAST:event_refreshActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        kosongkan();
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JOptionPane.showMessageDialog(null, "apakah anda yakin ingin keluar");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"apakah anda yakin untuk mengupdate data ini???",
               "confirmation",JOptionPane.YES_NO_OPTION);
        try {
            String sql = "update inventory_barang_masuk set kd_Barang=?,Nama_Barang=?,Tanggal_Masuk=?,Jumlah=?,Kategori=? where Kd_Barang='"+kode.getText()+"'";
            PreparedStatement st=conn.prepareStatement(sql);
            if(ok==0)
        try {
                st.setString(1, kode.getText());
                st.setString(2, nama.getText());
                st.setString(3, tglm.getText());
                st.setString(4, jumlah.getText());
                st.setString(5,(String) kategori.getSelectedItem());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update data berhasil");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update data berhasil");
            }
        
        } catch (Exception e) {
        }
        
            
        
        
    }//GEN-LAST:event_editActionPerformed

    private void txtcari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari2ActionPerformed
       tabel2();
    }//GEN-LAST:event_txtcari2ActionPerformed

    private void hapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus3ActionPerformed

    private void Cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari1ActionPerformed
         tabel1();
    }//GEN-LAST:event_Cari1ActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        tabel1();
    }//GEN-LAST:event_txtcariActionPerformed
            
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iventory_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iventory_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton Cari1;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus2;
    private javax.swing.JButton hapus3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JLabel kategorilbl;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode;
    private javax.swing.JButton masuk;
    private javax.swing.JTextField nama;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField tglk;
    private javax.swing.JTextField tglm;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtcari2;
    // End of variables declaration//GEN-END:variables
}
